// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSGb7WvyKfAAAayjqtAqEBcI9lt0e-mNw',
    appId: '1:576171790597:web:ef60281e3df4e98730a76c',
    messagingSenderId: '576171790597',
    projectId: 'shopshippay-cf372',
    authDomain: 'shopshippay-cf372.firebaseapp.com',
    storageBucket: 'shopshippay-cf372.appspot.com',
    measurementId: 'G-V2MLZ3489Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Um3LycYqjQ_jGaBCSAayk-uB0oljEMk',
    appId: '1:576171790597:android:2959e30a58b46b3c30a76c',
    messagingSenderId: '576171790597',
    projectId: 'shopshippay-cf372',
    storageBucket: 'shopshippay-cf372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVgA-lJFXCApmLpWUGR11dKJ825UYcBnU',
    appId: '1:576171790597:ios:8d13ef4b1c653cfa30a76c',
    messagingSenderId: '576171790597',
    projectId: 'shopshippay-cf372',
    storageBucket: 'shopshippay-cf372.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVgA-lJFXCApmLpWUGR11dKJ825UYcBnU',
    appId: '1:576171790597:ios:7aab2f8952ce70da30a76c',
    messagingSenderId: '576171790597',
    projectId: 'shopshippay-cf372',
    storageBucket: 'shopshippay-cf372.appspot.com',
    iosBundleId: 'com.example.shopApp.RunnerTests',
  );
}
